name: rarefold2
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core system libraries - let conda solve versions
  - _libgcc_mutex
  - _openmp_mutex
  - bzip2
  - ca-certificates
  - cuda
  - expat
  - ld_impl_linux-64
  - libffi
  - libgcc-ng>=12  # Updated to meet requirements
  - libgomp
  - libstdcxx-ng
  - libuuid
  - ncurses
  - openssl>=3.1.3  # Updated to meet Python 3.12 requirements
  - python=3.12
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip
  - pip:
      # Keep essential packages, remove strict version pins where possible
      - absl-py>=2.0.0
      - astunparse
      - biopython>=1.81
      - certifi
      - charset-normalizer
      - chex>=0.1.5
      - contextlib2
      - dm-haiku>=0.0.11
      - dm-tree
      - etils
      - flatbuffers
      - flax>=0.8.0
      - fsspec
      - gast
      - google-pasta
      - grpcio
      - h5py
      - idna
      - immutabledict
      - importlib-resources
      - jmp
      - keras>=3.4.0
      - libclang
      - markdown
      - markdown-it-py
      - markupsafe
      - mdurl
      - ml-collections
      - ml-dtypes
      - msgpack
      - namex
      - nest-asyncio
      - numpy>=1.26.0
      - opt-einsum
      - optax
      - optree
      - orbax-checkpoint
      - packaging
      - pandas>=2.2.0
      - protobuf
      - pygments
      - python-dateutil
      - pytz
      - pyyaml
      - requests
      - rich
      - scipy>=1.14.0
      - six
      - tabulate
      - tensorboard>=2.16.0
      - tensorboard-data-server
      - tensorflow>=2.16.0
      - tensorstore
      - termcolor
      - toolz
      - typing-extensions
      - tzdata
      - urllib3
      - werkzeug
      - wrapt
      - zipp
